language: c

branches:
  only:
    - master
    - release

dist: trusty
sudo: required

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
        - LLVM_VERSION="3.6.2"
        - LLVM_CONFIG="llvm-config-3.6"
        - config=debug
        - CC1=gcc-5
        - CXX1=g++-5
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
        - LLVM_VERSION="3.6.2"
        - LLVM_CONFIG="llvm-config-3.6"
        - config=release
        - CC1=gcc-5
        - CXX1=g++-5
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
        - LLVM_VERSION="3.7.1"
        - LLVM_CONFIG="llvm-config-3.7"
        - config=debug
        - CC1=gcc-5
        - CXX1=g++-5
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
        - LLVM_VERSION="3.7.1"
        - LLVM_CONFIG="llvm-config-3.7"
        - config=release
        - CC1=gcc-5
        - CXX1=g++-5
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
        - LLVM_VERSION="3.8.1"
        - LLVM_CONFIG="llvm-config-3.8"
        - config=debug
        - CC1=gcc-5
        - CXX1=g++-5
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
        - LLVM_VERSION="3.8.1"
        - LLVM_CONFIG="llvm-config-3.8"
        - config=release
        - CC1=gcc-5
        - CXX1=g++-5
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
        - LLVM_VERSION="3.9.0"
        - LLVM_CONFIG="llvm-config-3.9"
        - config=debug
        - CC1=gcc-5
        - CXX1=g++-5
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
        - LLVM_VERSION="3.9.0"
        - LLVM_CONFIG="llvm-config-3.9"
        - config=release
        - CC1=gcc-5
        - CXX1=g++-5
    - os: osx
      env:
        - LLVM_VERSION="3.7.1"
        - LLVM_CONFIG="llvm-config-3.7"
        - config=debug
        - CC1=clang-3.7
        - CXX1=clang++-3.7
    - os: osx
      env:
        - LLVM_VERSION="3.7.1"
        - LLVM_CONFIG="llvm-config-3.7"
        - config=release
        - lto=no
        - CC1=clang-3.7
        - CXX1=clang++-3.7
    - os: osx
      env:
        - LLVM_VERSION="3.8.1"
        - LLVM_CONFIG="llvm-config-3.8"
        - config=debug
        - CC1=clang-3.8
        - CXX1=clang++-3.8
    - os: osx
      env:
        - LLVM_VERSION="3.8.1"
        - LLVM_CONFIG="llvm-config-3.8"
        - config=release
        - lto=no
        - CC1=clang-3.8
        - CXX1=clang++-3.8
    - os: osx
      env:
        - LLVM_VERSION="3.9.0"
        - LLVM_CONFIG="llvm-config-3.9"
        - config=debug
        - CC1=clang-3.9
        - CXX1=clang++-3.9
    - os: osx
      env:
        - LLVM_VERSION="3.9.0"
        - LLVM_CONFIG="llvm-config-3.9"
        - config=release
        - lto=no
        - CC1=clang-3.9
        - CXX1=clang++-3.9


rvm:
  - 2.2.3

install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ];
    then
      wget "http://llvm.org/releases/${LLVM_VERSION}/clang+llvm-${LLVM_VERSION}-x86_64-linux-gnu-ubuntu-14.04.tar.xz";
      tar -xvf clang+llvm*;
      cd clang+llvm* && sudo mkdir /tmp/llvm && sudo cp -r * /tmp/llvm/;
      sudo ln -s /tmp/llvm/bin/llvm-config /usr/local/bin/${LLVM_CONFIG};
      cd -;
      wget ftp://ftp.csx.cam.ac.uk/pub/software/programming/pcre/pcre2-10.21.tar.bz2;
      tar -xjvf pcre2-10.21.tar.bz2;
      cd pcre2-10.21 && ./configure --prefix=/usr && make && sudo make install;
      cd -;
    fi;
  - if [ "${TRAVIS_OS_NAME}" = "osx" ];
    then
      brew update;
      brew install gmp; brew link --overwrite gmp;
      if [ "${LLVM_VERSION}" = "3.7.1" ];
      then
        brew install llvm37;
      fi;
      if [ "${LLVM_VERSION}" = "3.8.1" ];
      then
        brew install llvm38;
      fi;
      if [ "${LLVM_VERSION}" = "3.9.0" ];
      then
        brew install llvm;
        brew link --overwrite --force llvm;
        mkdir llvmsym;
        ln -s `which llvm-config` llvmsym/llvm-config-3.9;
        ln -s `which clang++` llvmsym/clang++-3.9;
        export PATH=llvmsym/:$PATH;
      fi;
      brew install pcre2 libressl;
    fi;

script:
  - make CC=$CC1 CXX=$CXX1 test-ci
